### ISSUE TITLE
Does the iOS client work?

### ISSUE THREAD

**Issue by joffrey-bion** [ln-12/kmm-websocket#3]
Hi, I tried running the iOS client code but it doesn't seem to work and I can't figure out why.
It just hangs without running any callback from the protocol delegate.

Did you have any success running this?

**Comment by ln-12** [comment]
I am using this code in production for half a year now and it works absolutely fine. Without any detail, I can't help you.

**Comment by joffrey-bion** [comment]
Thanks for your response! Sorry for the lack of details, it was merely a question about whether this was untested example code, or actually used production code.

I realized after quite a bit of investigation that the "hang" behaviour was because my iOS unit tests used `runBlocking`.

This effectively blocks the main thread and the main run loop (used to call WS callbacks) is actually never executed.
I had to jump through some hoops to manually run the main loop in the unit tests while waiting for the test code to finish.
